### ISSUE TITLE
Localisations e.g. https://*.google.co.uk/search*

### ISSUE THREAD

**Issue by grahamperrin** [EmerickH/EcoGoogle#2]
Currently: 

<https://github.com/EmerickH/EcoGoogle/blob/8ad332066dd76b14747d4a4dd8f31823f811f5d8/manifest.json#L29>

SVP can you add a match for UK-based searches? 

So, for example: 

https://www.google.co.uk/search?q=Waterfox&

– should benefit things through Ecosia. 

Merci

**Comment by EmerickH** [comment]
Hello,
I've changed it !
It's now on the master branch, I'm gonna do a release for Chrome and post it for Firefox.

Emerick
